### ISSUE TITLE
JBoss NameNotFoundException

### ISSUE THREAD

**Issue by gvsrini** [cerker/cuckoo-test#1]
I have configured sap-jco module, cuckoo-rar and cuckoo-test as per the documentation, but I am getting this exception.

Can you please help. Below is my log which clearly shows that JNDI is bound correctly;
## JNDI Bound

```
09:54:33,887 INFO  [org.jboss.as.deployment.connector] (MSC service thread 1-8) JBAS010401: Bound JCA ConnectionFactory [java:jboss/eis/sap/NSP]
```
## Full log

```
09:54:33,456 INFO  [org.cuckoo.ra.spi.CuckooManagedConnectionFactory] (MSC service thread 1-6) Registering new SAP destination named NSP
09:54:33,461 INFO  [org.cuckoo.ra.spi.CuckooResourceAdapter] (MSC service thread 1-6) Cuckoo-RA: registering JCo destination 'NSP'
09:54:33,468 WARNING [org.cuckoo.ra.jco.CuckooDestinationDataProvider] (MSC service thread 1-6) The eventListener is null!
09:54:33,471 INFO  [org.jboss.as.deployment.connector] (MSC service thread 1-6) JBAS010406: Registered connection factory java:jboss/eis/sap/NSP
09:54:33,480 INFO  [org.cuckoo.ra.spi.CuckooResourceAdapter] (MSC service thread 1-6) Starting Cuckoo Resource Adapter for SAP Version 1.1.0
09:54:33,882 INFO  [org.jboss.as.connector.deployers.RaXmlDeployer] (MSC service thread 1-6) IJ020002: Deployed: file:/D:/SAP/jboss-as/standalone/tmp/vfs/tempa8f396b0fad259e8/cuckoo-rar-1.1.0.rar-169df189e3bd184c/contents/
09:54:33,887 INFO  [org.jboss.as.deployment.connector] (MSC service thread 1-8) JBAS010401: Bound JCA ConnectionFactory [java:jboss/eis/sap/NSP]
09:54:33,890 INFO  [org.jboss.as] (MSC service thread 1-6) JBAS015951: Admin console listening on http://127.0.0.1:9990
09:54:33,891 INFO  [org.jboss.as] (MSC service thread 1-6) JBAS015874: JBoss AS 7.1.1.Final "Brontes" started in 4729ms - Started 208 of 287 services (78 services are passive or on-demand)
09:54:34,117 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018559: Deployed "cuckoo-test.war"
09:54:34,118 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 2) JBAS018559: Deployed "cuckoo-rar-1.1.0.rar"
10:01:08,328 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/cuckoo-test].[jsp]] (http--127.0.0.1-8080-1) Servlet.service() for servlet jsp threw exception: javax.naming.NameNotFoundException: eis/sap/NSP -- service jboss.naming.context.java.eis.sap.NSP
    at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:97)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
    at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
    at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
    at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_45]
    at org.cuckoo.ra.test.CuckooBean.loadData(CuckooBean.java:38) [classes:]
    at org.apache.jsp.index_jsp._jspService(index_jsp.java:67)
    at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70) [jbossweb-7.0.13.Final.jar:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:369) [jbossweb-7.0.13.Final.jar:]
    at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:326) [jbossweb-7.0.13.Final.jar:]
    at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:253) [jbossweb-7.0.13.Final.jar:]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:847) [jboss-servlet-api_3.0_spec-1.0.0.Final.jar:1.0.0.Final]
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161) [jbossweb-7.0.13.Final.jar:]
    at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [jbossweb-7.0.13.Final.jar:]
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [jbossweb-7.0.13.Final.jar:]
    at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671) [jbossweb-7.0.13.Final.jar:]
    at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930) [jbossweb-7.0.13.Final.jar:]
    at java.lang.Thread.run(Thread.java:744) [rt.jar:1.7.0_45]

```

**Comment by gvsrini** [comment]
Sorry, my mistake. CuckooBean.java already provides the definition for JBoss. Changed as follows and it works now!

```
    private static final String CONNECTION_FACTORY_JNDI_NAME = "java:jboss/eis/sap/NSP"; //works with JBoss
//    private static final String CONNECTION_FACTORY_JNDI_NAME = "eis/sap/NSP"; // works with Glassfish
```
